### ISSUE TITLE
Log all events

### ISSUE THREAD

**Issue by HellRemus** [affekri/QuickEconomy#25]
All events such as creating shops and banks, trying to destroys someone elses shop, accessing a shop, etc. should be logged in a separate log file with time stamps. This could be togglable and would ease debugging significantly.

**Comment by HellRemus** [comment]
Config could have a verbosity level parameter, were 0 is default, 1 is error only, 5 is all events, etc.

**Comment by affekri** [comment]
It seems that best practice for logging in Bukkit/Spigot/Paper plugins is to use the built in plugin.getLogger() method. Here all log entries are entered with timestamps and a verbosity level. These event will then be quite easy to filter out from the log file, using tools such as grep. However whether or not more events should be logged is definitely up for discussion. Currently the following is being logged: locking and unlocking chests(shops), failure to read from files(balance.yml and config.yml)
