### ISSUE TITLE
Shops can send income to non-existing players

### ISSUE THREAD

**Issue by HellRemus** [affekri/QuickEconomy#3]
When a shop is set to split the generated income between the shop owner and another player, the second username might not be in use. The plugin will create an account for a player by that name even if he/she/them don't exist.

**Comment by affekri** [comment]
This bug has now been fixed in commit [28ffe65](https://github.com/affekri/QuickEconomy/commit/28ffe654bceaa756d97383ffd80e0fcfa959a0c2).
